name: Publish to NPM

on:
  release:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "publish"
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
         
    - name: build script
      run: |
        npm install
        node scripts/build.js
      
    - name: publish
      run: npm publish --access public
      
